# Generated by Django 3.1.3 on 2020-11-28 15:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircularAreaGeom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geomValue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JburgBuildings',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('names', models.CharField(blank=True, max_length=255, null=True)),
                ('featuretype', models.CharField(blank=True, max_length=255, null=True)),
                ('buildingtype', models.CharField(blank=True, max_length=255, null=True)),
                ('isocountrycode', models.CharField(blank=True, max_length=255, null=True)),
                ('here_xyz', models.CharField(blank=True, max_length=255, null=True)),
                ('here_mom_meta', models.CharField(blank=True, max_length=255, null=True)),
                ('footprints', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='JburgLanduse',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cartotype', models.IntegerField()),
                ('featuretype', models.CharField(blank=True, max_length=255, null=True)),
                ('cartotypename', models.CharField(blank=True, max_length=255, null=True)),
                ('here_xyz', models.CharField(blank=True, max_length=255, null=True)),
                ('here_mom_meta', models.CharField(blank=True, max_length=255, null=True)),
                ('cartoname', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='MajorWorldCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=120)),
                ('cntry_name', models.CharField(max_length=120)),
                ('pop_class', models.CharField(max_length=120)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
