# Generated by Django 3.1.3 on 2020-12-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CircularAreaGeom',
        ),
        migrations.DeleteModel(
            name='JburgBuildings',
        ),
        migrations.DeleteModel(
            name='JburgLanduse',
        ),
        migrations.DeleteModel(
            name='MajorWorldCities',
        ),
    ]
